version: '3.0'

services:
  db:
    image: mysql:8.0.17
    container_name: mysql_DB
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '${DB_PORT}:3306'

  adminer:
    image: adminer
    container_name: adminer
    depends_on: 
      - db
    ports:
      - '8082:8080'
volumes:
    db_data:
